#:kivy 1.0

<Introduccion>:
    name: "intro"
    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "[u]Monitor Estadístico TECx[/u]"
                markup: True
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Esta aplicación trabaja con un algoritmo que fragmenta las respuestas para"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.9}
                font_size: (root.width**2 + root.height**2) / 15.5**4       

            Label:
                text: "completar con ellas distintos formularios electrónicos que impidan reconstruir los"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.85}
                font_size: (root.width**2 + root.height**2) / 15.5**4          

            Label:
                text: "datos ingresados por su empresa. De esta manera está garantizado el anonimato."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.8}
                font_size: (root.width**2 + root.height**2) / 15.5**4 

            Label:
                text: "En esta primera medición, el objetivo es relevar los perfiles de RRHH transversales a todos"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 15.5**4        

            Label:
                text: "los segmentos de la economía del conocimiento. Para próximas mediciones se trabajará con "
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 15.5**4                                                                    
                
            Label:
                text: "cada segmento en la medición de RRHH específicos."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.65}
                font_size: (root.width**2 + root.height**2) / 15.5**4  

            Label:
                text: "Al seleccionar la opción continuar aparecerá una botonera con cada perfil de RRHH."
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.4}
                font_size: (root.width**2 + root.height**2) / 15.5**4

            Label:
                text: "Podrá ingresar a cualquier perfil. Podrá dejar campos en blanco."
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.35}
                font_size: (root.width**2 + root.height**2) / 15.5**4              

            Label:
                text: "Podrá, también, regresar y modificar datos."
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.3}
                font_size: (root.width**2 + root.height**2) / 15.5**4       

            Label:
                text: "Desarrollado por EconomicTrends"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.1}
                font_size: (root.width**2 + root.height**2) / 17**4    

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.8, 0.17
            text: "Continuar al formulario"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
                root.perfil_csv()            
            on_release:
                app.root.current = "main"                  
                root.manager.transition.direction = "left"   


<MainWindow>:
    name: "main"
    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        GridLayout:
            cols:2                
            Button:
                text: "Líder de Desarrollo / Project Manager / SDM / Scrum Master"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil1"
                    root.manager.transition.direction = "left"
            Button:
                text: "Cloud Engineer"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil1b"
                    root.manager.transition.direction = "left"                    
            Button:
                text: "Desarrollador de Software Back End"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil2a"
                    root.manager.transition.direction = "left"  
            Button:
                text: "Desarrollador de Software Front End"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil2b"
                    root.manager.transition.direction = "left"
            Button:
                text: "Desarrollador de Software Full Stack"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil2c"
                    root.manager.transition.direction = "left"                                        
            Button:
                text: "Arquitecto de Software"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil3"
                    root.manager.transition.direction = "left" 
            Button:
                text: "Consultor BI - Business Intelligence"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil4"
                    root.manager.transition.direction = "left" 
            Button:
                text: "Analista de negocios"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil5"
                    root.manager.transition.direction = "left"   
            Button:
                text: "Diseñador Web"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil6"
                    root.manager.transition.direction = "left"        
            Button:
                text: "Analista UI/UX (usabilidad)"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil7"
                    root.manager.transition.direction = "left"      
            Button:
                text: "Tester / Analista tester"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil8"
                    root.manager.transition.direction = "left"    
            Button:
                text: "QA Automation"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil19"
                    root.manager.transition.direction = "left"                        
            Button:
                text: "Analista de Calidad"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil9"
                    root.manager.transition.direction = "left"    
            Button:
                text: "IT Manager"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil10"
                    root.manager.transition.direction = "left"    
            Button:
                text: "Administardor de Base de Datos (DBA)"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil11"
                    root.manager.transition.direction = "left"        
            Button:
                text: "Analista Funcional"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil12"
                    root.manager.transition.direction = "left"    
            Button:
                text: "Analista Big Data - Data Scientist"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil13"
                    root.manager.transition.direction = "left"  
            Button:
                text: "Experto en Machine Learning"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil21"
                    root.manager.transition.direction = "left"                           
            Button:
                text: "Analista Middleware"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil14"
                    root.manager.transition.direction = "left"
            Button:
                text: "Soporte Técnico"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil15"
                    root.manager.transition.direction = "left"        
            Button:
                text: "Especialista en Seguridad de la Información"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil16"
                    root.manager.transition.direction = "left"    
            Button:
                text: "Implementador Configuration Manager"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil17"
                    root.manager.transition.direction = "left"        
            Button:
                text: "Implementador Software de Gestión"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil18"
                    root.manager.transition.direction = "left"      
            Button:
                text: "DevOps"
                on_press: 
                    self.background_color = (0/255,51/255,102/255,1)
                on_release:
                    app.root.current = "perfil20"
                    root.manager.transition.direction = "left" 

        Button:
            text: "Cerrar APP y Enviar Respuestas"
            font_size: (root.width**2 + root.height**2) / 14**4
            size_hint: 0.2, 0.2
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                on_release: root.btn()


<Popups>:    
    Label:
        text: "A continuación se hará el envío de sus respuestas." 
        size_hint: 0.6, 0.3
        pos_hint: {"x":0.2, "top":0.99}

    Label:
        text: "Esto puede demorar entre 1 y 2 minutos,"  
        size_hint: 0.6, 0.3
        pos_hint: {"x":0.2, "top":0.89}

    Label:
        text: "por favor no cierre el aplicativo." 
        size_hint: 0.6, 0.3
        pos_hint: {"x":0.2, "top":0.79}        
        
    Button:
        text: "Continuar"
        # set size of the button
        size_hint: 1, 0.4
        # set position of the button  
        pos_hint: {"x":0, "y":0.1}
        on_press: 
            self.background_color = (0/255,51/255,102/255,1)
        on_release:    
            root.fin()

<Perfil1>: #Líder de Desarrollo / Proyect Manager (PM)
    name: "perfil1"
    pm: pm
    sdm: sdm
    scr: scr

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Líder de Desarrollo / Project Manager (PM)"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: SDM (Service Delivery Manager)"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Lograr que el proyecto se desarrolle dentro de los alcances, costos y calidad establecidos en los plazos previstos con la menor"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "cantidad de inconvenientes, anticipando posibles problemas o desvíos y tomando decisiones correctivas o proponiendo alternativas a la gerencia"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Gerente de Proyectos o PM:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: pm
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Gerente de Operaciones de un Cliente / Service Delivery Manager:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: sdm
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Scrum Master / Agile Coach:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: scr
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()
                
<Perfil1b>: #Cloud Engineer
    name: "perfil1b"
    ceng: ceng

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Cloud Engineer"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Cloud Consultant / Cloud Administrator / Cloud Specialist / Cloud Analyst"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4                       
    
            Label:
                text: "[u]Misión[/u]: Diseñar, implementar y mantener infraestructuras en la nube."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4                             

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Cloud Engineer:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: ceng
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()                 

<Perfil2a>: #Desarrollador de Software Back End
    name: "perfil2a"
    app_cs: app_cs
    desar_web: desar_web
    desar_juegos: desar_juegos
    desar_app_mov: desar_app_mov
    desar_sist_emb: desar_sist_emb

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Desarrollador de Software Back End"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Programador Back End / Analista-programador Back End / Developer Back End"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Participar del proceso de programación / implementación teniendo como entrada las especificaciones de software y ajustándose"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: " a tiempos y estándares de calidad y trabajo de la organización y del proyecto, ocupándose de la arquitectura interna  de la web, aplicación o software."
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Desarrollador de aplicaciones cliente-servidor:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: app_cs
                pos_hint: {"x":0.8, "top":0.75-0.125}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Desarrollador Web:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_web
                pos_hint: {"x":0.8, "top":0.75-0.125*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Desarrollador de juegos / Aplicaciones lúdicas:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: desar_juegos
                pos_hint: {"x":0.8, "top":0.75-0.125*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
    
            Label:
                text: "Desarrollador de Aplicaciones Móviles:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*4}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_app_mov
                pos_hint: {"x":0.8, "top":0.75-0.125*4}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Desarrollador de Sistemas Embebidos:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*5}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_sist_emb
                pos_hint: {"x":0.8, "top":0.75-0.125*5}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1) 
            on_release:            
                root.manager.transition.direction = "right" 
                root.submit()
   
<Perfil2b>: #Desarrollador de Software Front End
    name: "perfil2b"
    app_cs_b: app_cs_b
    desar_web_b: desar_web_b
    desar_juegos_b: desar_juegos_b
    desar_app_mov_b: desar_app_mov_b
    desar_sist_emb_b: desar_sist_emb_b

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Desarrollador de Software Front End"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Programador Front End / Analista-programador Front End / Developer Front End"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Participar del proceso de programación / implementación teniendo como entrada las especificaciones de software y ajustándose"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "a tiempos y estándares de calidad y trabajo de la organización y del proyecto, ocupándose de la inerfaz gráfica para el usuario."
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Desarrollador de aplicaciones cliente-servidor:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: app_cs_b
                pos_hint: {"x":0.8, "top":0.75-0.125}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Desarrollador Web:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_web_b
                pos_hint: {"x":0.8, "top":0.75-0.125*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Desarrollador de juegos / Aplicaciones lúdicas:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: desar_juegos_b
                pos_hint: {"x":0.8, "top":0.75-0.125*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
    
            Label:
                text: "Desarrollador de Aplicaciones Móviles:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*4}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_app_mov_b
                pos_hint: {"x":0.8, "top":0.75-0.125*4}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Desarrollador de Sistemas Embebidos:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*5}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_sist_emb_b
                pos_hint: {"x":0.8, "top":0.75-0.125*5}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1) 
            on_release:            
                root.manager.transition.direction = "right" 
                root.submit()

<Perfil2c>: #Desarrollador de Software Full Stack
    name: "perfil2c"
    app_cs_c: app_cs_c
    desar_web_c: desar_web_c
    desar_juegos_c: desar_juegos_c
    desar_app_mov_c: desar_app_mov_c
    desar_sist_emb_c: desar_sist_emb_c

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Desarrollador de Software Full Stack"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Programador Full Stack / Analista-programador Full Stack / Developer Full Stack"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Participar del proceso de programación / implementación teniendo como entrada las especificaciones de software y ajustándose a tiempos y"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "estándares de calidad y trabajo de la organización y del proyecto, capaz de ocuparse tanto de la arquitectura interna como de la inerfaz gráfica para el usuario."
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Desarrollador de aplicaciones cliente-servidor:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: app_cs_c
                pos_hint: {"x":0.8, "top":0.75-0.125}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Desarrollador Web:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_web_c
                pos_hint: {"x":0.8, "top":0.75-0.125*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Desarrollador de juegos / Aplicaciones lúdicas:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: desar_juegos_c
                pos_hint: {"x":0.8, "top":0.75-0.125*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
    
            Label:
                text: "Desarrollador de Aplicaciones Móviles:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*4}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_app_mov_c
                pos_hint: {"x":0.8, "top":0.75-0.125*4}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Desarrollador de Sistemas Embebidos:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.12*5}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: desar_sist_emb_c
                pos_hint: {"x":0.8, "top":0.75-0.125*5}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1) 
            on_release:            
                root.manager.transition.direction = "right" 
                root.submit()

<Perfil3>: #Arquitecto de Software
    name: "perfil3"    
    app_mov: app_mov
    sist_em: sist_em

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Arquitecto de Software"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Diseñador de Software / Diseñador de Soluciones / Desarrollador Senior"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: En cooperación con el Líder de Proyecto, participa en la toma de decisiones adecuadas para lograr una arquitectura"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "ajustándose a tiempos y estándares de calidad y trabajo de la organización y del proyecto"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Aplicaciones móviles:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: app_mov
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Sistemas embebidos:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: sist_em
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()

<Perfil4>: #Consultor BI - Business Intelligence
    name: "perfil4"
    desar: desar
    esp_inf: esp_inf
    analist: analist

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Consultor BI - Business Intelligence"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Analista Business Intelligence / Especialista en Business Intelligence"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Proveer de nuevo conocimiento relevante para la toma de decisiones en la organización"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Desarrollador:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: desar
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Especialista en informes:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: esp_inf
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Analista:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: analist
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
    
        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()  

<Perfil5>: #Analista de Negocios
    name: "perfil5"
    ap_erp_crm: ap_erp_crm
    esp_proc: esp_proc
    esp_ind: esp_ind

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Analista de Negocios"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Consultor Funcional / Analista Funcional / Analista de Procesos"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Acompañar los cambios y evolución de las organizaciones brindando"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "soluciones de valor agregado sobre sus procesos de negocios y aplicaciones"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Aplicaciones ERP / CRM:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: ap_erp_crm
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Especialista en procesos: financieros, logísticos, producción:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: esp_proc
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Especialista en industrias: consumo masivo, financieros, retail, etc.:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: esp_ind
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()                                  

<Perfil6>: #Diseñador Web
    name: "perfil6"
    uxd: uxd
    webd: webd
    mkt: mkt

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Diseñador Web"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Maquetador Web / UI Developer / Front-End Designer"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Es quien se encarga de la identidad visual, la coherencia y consistencia gráfica del sitio web, priorizando la comunicación"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "y una interfaz de usuario responsiva, seleccionando los elementos que la componen y codificando los diseños en lenguajes HTML, CSS y JS"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "UX Developer:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: uxd
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "WEBDeveloper:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: webd
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Marketing Online:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: mkt
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()                     

<Perfil7>: #Analista UI/UX (Usabilidad)
    name: "perfil7"    
    research: research
    analisis: analisis
    prot_inter: prot_inter
    test_us: test_us

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Analista UI/UX (Usabilidad)"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Analista de Usabilidad / Analista UI/UX / Analista de Experiencia de Usuario / Consultor de Usabilidad"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "/ Consultor UI/UX / Diseñador UI/UX / User Insight Analyst / Experience Designer / User Experience Analyst."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4  

            Label:
                text: "[u]Misión[/u]: Optimizar la experiencia del usuario cuando interactúa con un software consiguiendo la mayor satisfacción y mejor experiencia de uso posible con el"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "mínimo esfuerzo. Lograr, utilizando técnicas de usabilidad, que un producto sea lo más eficaz, eficiente y satisfactorio para los diferentes usuarios y contextos"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.86}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Research (en general o en técnica específica):"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: research
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Análisis:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: analisis
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Prototipado de interfaz de usuarios:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: prot_inter
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
    
            Label:
                text: "Test de usuarios / Test de usabilidad:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*4}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: test_us
                pos_hint: {"x":0.8, "top":0.75-0.155*4}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1) 
            on_release:            
                root.manager.transition.direction = "right" 
                root.submit()

<Perfil8>: #Tester / Analista Tester
    name: "perfil8"
    orient_tec: orient_tec
    orient_func: orient_func
    orient_seg: orient_seg

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Tester / Analista Tester"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Líder de Pruebas / Analista de Control de Calidad"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Asegurar que el software o pieza de software funcione de acuerdo con los requisitos y trabaje con sus interfaces"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "de la forma esperada, detectando en forma temprana defectos y evitando propagación y llegada al cliente (interno o externo)"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Orientación técnica (stress, volumen, performance, etc.):"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: orient_tec
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Orientación funcional:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: orient_func
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Orientación seguridad (técnicas de hackeo, etc.):"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: orient_seg
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()

<Perfil19>: #QA Automation
    name: "perfil19"
    qa: qa

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "QA Automation"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4
    
            Label:
                text: "[u]Misión[/u]: Decide cuáles de las pruebas detalladas en el plan de pruebas tiene prioridad para automatizarse."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "QA Automation:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: qa
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil9>: #Analista de Calidad
    name: "perfil9"
    iso: iso
    itil: itil
    cmmi: cmmi

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Analista de Calidad"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: QA / Analista de Procesos"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Proveer un marco de metodología y estandarización a la Organización y sus Proyectos, en dos importantes ramas:"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "calidad en procesos y calidad en producto, detectando en forma temprana las causas de los defectos y evitando su propagación"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "ISO 9001 - ISO 27001:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: iso
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
       
            Label:
                text: "Modelos de Calidad para servicios TI (ITIL / ISO 20000):"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'
                
            TextInput:
                id: itil
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "CMMI:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'               
    
            TextInput:
                id: cmmi
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)
            on_release:
                root.manager.transition.direction = "right"            
                root.submit()

<Perfil10>: #IT Manager
    name: "perfil10"
    datcenter: datcenter
    rout_switch: rout_switch
    video: video
    voice: voice
    redes: redes
    seg: seg

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "IT Manager: Administrador de Redes, Comunicaciones y Sistemas Operativos"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "[u]Otras denominaciones[/u]: Soporte de Infraestructura IT / Soporte de Redes / Especialista en Redes "
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "/ Técnico en Redes / Ingeniero en Redes / Administrador de Redes, Comunicaciones y Sistemas Operativos"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "[u]Misión[/u]: Administrar la operación, seguridad y mantenimiento de la infraestructura"
                markup: True                
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4                                    
                
            Label:
                text: "de redes asegurando la calidad y performance de los servicios de la Organización"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.86}
                font_size: (root.width**2 + root.height**2) / 17**4 

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Data Center:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: datcenter
                pos_hint: {"x":0.4, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Routing and Switching:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'

            TextInput:
                id: rout_switch
                pos_hint: {"x":0.4, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Video:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15*3}
                font_size: (root.width**2 + root.height**2) / 15.5**4 
                text_size: self.size
                halign: 'left'    

            TextInput:
                id: video
                pos_hint: {"x":0.4, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Voice:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.55, "top":0.75-0.15}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'

            TextInput:
                id: voice
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
        
            Label:
                text: "Redes Wireless:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.55, "top":0.75-0.15*2}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'

            TextInput:
                id: redes
                pos_hint: {"x":0.8, "top":0.75-0.155*2}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "Seguridad:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.55, "top":0.75-0.15*3}                
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'

            TextInput:
                id: seg
                pos_hint: {"x":0.8, "top":0.75-0.155*3}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4
                
        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1) 
            on_release:            
                root.manager.transition.direction = "right" 
                root.submit()

<Perfil11>: #Administrador de Base de Datos (DBA)
    name: "perfil11"
    dba: dba

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Administrador de Base de Datos (DBA)"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Analista de Bases de Datos / DBA (Database Administrator)"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Garantizar y optimizar la seguridad, integridad y estabilidad de las bases de datos que"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "administran la información de las operaciones del negocio, para que siempre estén disponibles con tiempos de respuesta óptimos,"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: " según las diferentes áreas de la compañía. En términos tecnológicos: asegurar la continuidad operacional"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.86}
                font_size: (root.width**2 + root.height**2) / 17**4                                                  
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Administrador de Base de Datos (DBA):"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: dba
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil12>: #Analista funcional
    name: "perfil12"
    afunc: afunc

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Analista Funcional"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Analista de Sistemas / Analista Técnico Funcional / Business Partner"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Establecer los requisitos funcionales del sistema"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4                                                           
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Analista Funcional:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: afunc
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil13>: #Analista Big Data - Data Scientist
    name: "perfil13"
    dscience: dscience

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Analista Big Data - Data Scientist"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Experto en Big Data / Analista Data Scientist / 'Chief data officer' (CDO) / Analista Digital"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Responsable de los datos empresariales y de la estrategia de la información. Debe diseñar, implantar y optimizar una estrategia"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: " a largo plazo del manejo de la información en la empresa. Es el encargado de analizar datos cuantitativos y cualitativos del entorno digital para"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: "extraer información de valor que ayude a tomar decisiones"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.86}
                font_size: (root.width**2 + root.height**2) / 17**4                                                  
                
            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Analista Big Data - Data Scientist:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: dscience
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil14>: #Analista Middleware
    name: "perfil14"
    midd: midd

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Analista Middleware"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Administrador de Middleware / Ingeniero en Soporte Middleware / Ingeniero Middleware / Consultor Middleware"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Es el responsable de la administración de aplicaciones Middleware (programas que asisten a una aplicación para interactuar"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "o comunicarse con otras aplicaciones, o paquetes de programas, redes, hardware y/o sistemas operativos)"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Analista Middleware:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: midd
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil15>: #Soporte Técnico
    name: "perfil15"
    soporte: soporte

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Soporte Técnico"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Technical Support Engineer / Global Support Engineer / Atención al Usuario / Customer Care"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Asistir al usuario en las dudas sobre el uso o resolución de problemas de la aplicación una vez que esta haya pasado la etapa de desarrollo"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Soporte Técnico:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: soporte
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil16>: #Especialista en Seguridad de la Información
    name: "perfil16"
    esp_seg: esp_seg

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Especialista en Seguridad de la Información"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Analista de Seguridad / Especialista en Seguridad Informática"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Proveer un marco de metodología y estandarización de seguridad de información a la organización y sus proyectos,"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "detectando en forma temprana causas de desvíos, implementando y administrando sistemas, políticas y normatividad de seguridad informática"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Especialista en Seguridad de la Información:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: esp_seg
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil17>: #Implementador Configuration Manager
    name: "perfil17"
    config: config

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Implementador Configuration Manager"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Configuration Manager / Release Manager / Implementation Manager / Implementador de Despliegues"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Mantenimiento de la integridad de la configuración a lo largo del ciclo de vida de los componentes de software,"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "mediante actividades de planificación, despliegue, control y auditoría"
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Implementador Configuration Manager:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: config
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil18>: #Implementador Software de Gestión
    name: "perfil18"
    soft_gest: soft_gest

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Implementador Software de Gestión"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Analista Técnico"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4       

            Label:
                text: "[u]Misión[/u]: Diseñar e implementar la parametrización requerida para reflejar las particularidades de cada proyecto"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Implementador Software de Gestión:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: soft_gest
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil20>: #DevOps
    name: "perfil20"
    devops: devops

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "DevOps"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: Site Reliability Engineer / Devops Consultant"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4                       
    
            Label:
                text: "[u]Misión[/u]: Transformar culturalmente el área de development. Hacer que todo"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "el ciclo de vida de la aplicación sea mejor y tenga menores errores cuando llegue a producción."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "DevOps:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: devops
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 

<Perfil21>: #Experto en Machine Learning
    name: "perfil21"
    malearn: malearn

    GridLayout:
        cols:1
        canvas.before:
            Color:
                rgba:(0/255,51/255,102/255,1)
            Rectangle:
                pos:self.pos
                size:self.size
        
        FloatLayout:
            size: root.width, root.height/2
            padding: 15
            
            Label:
                text: "Experto en Machine Learning"
                #color: (0/255 ,0/255, 0/255,1)
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":1}
                font_size: (root.width**2 + root.height**2) / 14**4

            Label:
                text: "[u]Otras denominaciones[/u]: - "
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.95}
                font_size: (root.width**2 + root.height**2) / 17**4                       
    
            Label:
                text: "[u]Misión[/u]: Diseño de software de ejecución automática para automatizar modelos predictivos,"
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.92}
                font_size: (root.width**2 + root.height**2) / 17**4             

            Label:
                text: "incluyendo modelos de árboles de decisión, random forest, redes neuronales, entre otros."
                markup: True
                size_hint: 0.8, 0.2
                pos_hint: {"x":0.1, "top":0.89}
                font_size: (root.width**2 + root.height**2) / 17**4   

            Label:
                text: "Indique, para cada especialidad, la cantidad de búsquedas activas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.75}
                font_size: (root.width**2 + root.height**2) / 14.5**4

            Label:
                text: "Puede dejar en blanco las especialidades sin búsquedas actuales"
                size_hint: 0.4,0.1
                pos_hint: {"x":0.3, "top":0.7}
                font_size: (root.width**2 + root.height**2) / 17**4                
                            
            Label:
                text: "Experto en Machine Learning:"
                size_hint: 0.4,0.08
                pos_hint: {"x":0.1, "top":0.75-0.15}
                font_size: (root.width**2 + root.height**2) / 15.5**4
                text_size: self.size
                halign: 'left'                
    
            TextInput:
                id: malearn
                pos_hint: {"x":0.8, "top":0.75-0.155}
                size_hint: 0.12, 0.09
                multiline: False
                font_size: (root.width**2 + root.height**2) / 14**4

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.6, 0.15
            text: "Ingresar valores y volver al menú anterior"
            font_size: (root.width**2 + root.height**2) / 14**4
            on_press: 
                self.background_color = (0/255,51/255,102/255,1)   
            on_release:
                root.manager.transition.direction = "right"            
                root.submit() 
             